<?php
/**
 * Trust Payments Magento 2
 *
 * This Magento 2 extension enables to process payments with Trust Payments (https://www.trustpayments.com//).
 *
 * @package TrustPayments_Payment
 * @author wallee AG (http://www.wallee.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/** @var $block \TrustPayments\Payment\Block\DeviceSession */
?>
<script type="text/x-magento-init">
{
    "*": {
        "TrustPayments_Payment/js/trustpayments-device": {
            "scriptUrl" : "<?=$block->escapeHtml($block->getScriptUrl())?>",
            "identifierUrl" : "<?=$block->escapeHtml($block->getSessionIdentifierUrl())?>"
        }
    }
}
</script>